version: '3'

services:

  nginx:
    image: nginx:1.25.4
    volumes:
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/etc/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./homepage/src/:/static_site/:ro
    ports:
      - 8000:8000